import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";

const sora = Montserrat({
  variable: "--font-mont",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Shait A. Sarkar",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${sora.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
