import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { ThemeProvider } from "next-themes";

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"]
})


export const metadata: Metadata = {
  title: "Shait A. Sarkar",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${sora.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class" // adds theme class to <html>
          defaultTheme="light" // fallback theme
          enableSystem={true} // respects system preference
        >

          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
